import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "sonner";
import { SignUpModal } from "@/components/modals/SignUpModal";
import { LoadingBar } from "@/components/loading-bar";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <Toaster />
          <NextTopLoader color="#1DB954" />
          {children}
          <SignUpModal />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
